### ISSUE TITLE
Error - service missing

### ISSUE THREAD

**Issue by tdao-usesi** [aws-actions/amazon-ecs-deploy-task-definition#312] opened 2022-03-04 16:53 UTC
The logs show that my workflow is failing because my service is missing, but the pawebapp-service is currently running and the status is active. Could there be a problem with permissions?

`Error: arn:aws:ecs:us-east-2:***:service/pawebapp-service is MISSING`

**Comment by belly-qoala** [comment] 2023-03-01 04:14
hi @tdao-usesi , i face same issue. In my case the root cause is because I used wrong ECS cluster name.
Hope that help

**Comment by jamesbraza** [comment] 2023-11-01 16:49
For me, I was getting this error because the AWS ECS service had not yet been created.

Our DevOps team uses Terraform, and basically they forgot Terraform code for `aws_ecs_service`:

```terraform
resource "aws_ecs_service" "<redacted>" {
  name                               = "<redacted>"
  cluster                            = aws_ecs_cluster.this.id
  task_definition                    = aws_ecs_task_definition.<redacted>.arn
  desired_count                      = 1
  launch_type                        = "<redacted>"
  deployment_maximum_percent         = 200
  deployment_minimum_healthy_percent = 100
  enable_execute_command             = true
  propagate_tags                     = "SERVICE"

  ...
}
```

**Comment by amazreech** [comment] 2024-08-14 14:17
Based on the responses to the original request on this issue, I think the issue here might already. I will be closing this issue, please feel free to open a new issue if the issue persists. Thanks!

**Closed by amazreech** 2024-08-14 14:17 UTC
