### ISSUE TITLE
 Failed to register task definition in ECS: Unrecognized collection type class com.amazonaws.madison.frontend.RegisterTaskDefinitionRequest

### ISSUE THREAD

**Issue by RahulKumarTechahead** [aws-actions/amazon-ecs-deploy-task-definition#610] opened 2024-08-12 15:08 UTC
Run aws-actions/amazon-ecs-deploy-task-definition@v2
  with:
    task-definition: rendered-task-definition.json
    service: ***
    cluster: ***
    wait-for-service-stability: true
    codedeploy-appspec: rendered-service-definition.json
  env:
    AWS_ACCOUNT_ID: ***
    AWS_REGION: us-west-2
    AWS_DEFAULT_REGION: us-west-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    ARN: 
Error: Failed to register task definition in ECS: Unrecognized collection type class com.amazonaws.madison.frontend.RegisterTaskDefinitionRequest
Error: Unrecognized collection type class com.amazonaws.madison.frontend.RegisterTaskDefinitionRequest

**Comment by amazreech** [comment] 2024-08-12 20:11
Hi @RahulKumarTechahead, Thank you for reaching out with your question. For best assistance on this issue I recommend contacting AWS support as they should have the expertise needed to address this. You can reach AWS Support through here: https://docs.aws.amazon.com/awssupport/latest/user/getting-started.html

Please let me know if there is anything else I can help you with.

**Comment by kg-aws** [comment] 2024-08-26 13:36
Hi @RahulKumarTechahead - I hope you were able to reach out to the AWS support. If you think the issue is related to this repository feel free to drop the logs or error messages that can help use debug the issue. If not, we plan to close the issue.

**Comment by ryanshepps** [comment] 2024-08-28 19:41
I ran into this issue when I was only including the container definitions in my task-definition.json:

```json
[
    {
        "name": "...",
        "image": "...",
        ...
    }
]
```

Defining the whole task definition fixed it:

```json
{
    "containerDefinitions": [
        {
            "name": "...",
            "image": "..."
        }
    ],
    "memory": 2048,
    "cpu": 1024,
    "networkMode": "awsvpc",
    "family": "...",
    "executionRoleArn": "...",
    "requiresCompatibilities": ["FARGATE"]
}
```

**Comment by amazreech** [comment] 2024-09-05 20:49
Thanks for your response @ryanshepps!

@RahulKumarTechahead I will close this issue for now please feel free to open a new issue if this persists. Thank you!

**Closed by amazreech** 2024-09-05 20:49 UTC
