### ISSUE TITLE
Stop tasks first then start new task to use full instance resource

### ISSUE THREAD

**Issue by abinhho** [aws-actions/amazon-ecs-deploy-task-definition#181] opened 2021-03-09 08:41 UTC
In the pass, i used ecs-cli to deploy and via `es_params` i can config a task using full resource of EC2 instance.
EX: EC2 instance micro: 1GB, then memory on es params config around ~1000MB.

But since I use github workflow, i have to reduce memory to 500MB to make it works. Because always have a running task.
How can i make it 1000MB same with deploy via `ecs-cli`?

**Comment by paragbhingre** [comment] 2021-03-26 20:50
@abinhho Thanks for posting this question.
Could you please take a look at this [comment](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/113#issuecomment-717465045) and let me know if it works for you? 
Because looks like you are also facing the similar kind of issue while deployment.

**Comment by allisaurus** [comment] 2021-04-08 15:58
Closing as this appears to be a duplicate of https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/113 which has been addressed. But feel free to reopen if this is not the case.

**Closed by allisaurus** 2021-04-08 15:58 UTC
Labels: investigating
